### ISSUE TITLE
Transparent Proxy not Work on Raspberry Pi 3

### ISSUE THREAD

**Issue by sh1va73** [brainfucksec/kalitorify#20] opened 2019-06-27 14:07 UTC
I installed Kalitorify on a Raspberry and works fine. I have internet and different IP.
After I close Kalitorify I have no internet connection. I see that resolve.conf is deleted.
When I restore and try again it happens again.

**Comment by brainfucksec** [comment] 2019-06-29 06:09
Hi @sh1va73, thanks for your reporting. You have `resolvconf` installed?

**Comment by sh1va73** [comment] 2019-06-29 08:38
Yes it is installed and you are correct; it changes the settings of the file somehow.

**Comment by sh1va73** [comment] 2019-06-29 15:37
I just tested again on a fresh Kali install on Raspberry Pi 3. My resolv.conf file is again overwritten after starting Kalitorify. After closing Kalitorify then the file is not restored.

**Comment by brainfucksec** [comment] 2019-06-30 09:45
Did you install kalitorify as indicated in the README or you run it inside the program folder?
Do you receive any errors in the terminal output?

**Comment by sh1va73** [comment] 2019-06-30 09:47
I installed like indicated and I did not get errors. This is on Raspberry Pi. I have another installation on VirtualBox and there it is working fine.

**Comment by brainfucksec** [comment] 2019-06-30 10:10
In the past there have been similar problems with the Raspberry Pi (related to the kernel and iptables).
Here the problem is not only the resolv.conf file but there are errors at startup.
I need time to replicate the error or to find solutions, I update the discussion as soon as I know anything about the problem.

**Comment by brainfucksec** [comment] 2019-07-30 19:51
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.

**Closed by brainfucksec** 2019-07-30 19:51 UTC
Labels: bug, expiring
